"""
Django settings for student_management project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 团队共享配置
# =============================================================================
# 团队共享数据库路径配置
# 获取项目根目录的共享数据文件夹
SHARED_DATA_DIR = BASE_DIR.parent / 'shared_data'

# 确保共享数据目录存在
os.makedirs(SHARED_DATA_DIR, exist_ok=True)

# 共享数据库文件路径
SHARED_DB_PATH = SHARED_DATA_DIR / 'team_shared.db'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fz*!$@)z9xf_(4x6!ag(mz7(_=9!861^&9-46#0oj925l_pg8@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 扩展允许的主机，支持局域网访问
ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    'testserver',
    '0.0.0.0',  # 允许所有IP访问（开发环境）
    # 如果团队成员有固定IP，可以在这里添加
    # '192.168.1.100',  # 示例IP地址
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'students',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'student_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'student_management.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# 团队共享数据库配置
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': SHARED_DB_PATH,
        'OPTIONS': {
            # SQLite团队共享优化配置
            'timeout': 30,  # 设置超时时间为30秒
            'check_same_thread': False,  # 允许多线程访问
        },
        # 连接设置优化
        'CONN_MAX_AGE': 60,  # 连接最大生存时间60秒
    }
}

# 会话配置（支持多实例共享）
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # 使用数据库存储会话
SESSION_COOKIE_AGE = 600  # 会话保持10分钟（600秒）
SESSION_SAVE_EVERY_REQUEST = True  # 每次请求都更新会话过期时间
# 启用会话安全设置
SESSION_COOKIE_SECURE = False  # 开发环境设为False，生产环境设为True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# 缓存配置（可选，用于提升性能）
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': SHARED_DATA_DIR / 'cache',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # 仅保留最小长度验证器
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 6,  # 降低最小长度要求到6位
        }
    },
    # 暂时移除所有其他验证器以提供最佳用户体验
    # UserAttributeSimilarityValidator - 移除以允许用户名相关密码
    # CommonPasswordValidator - 移除以允许常见密码
    # NumericPasswordValidator - 移除以允许纯数字密码
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login/Logout URLs
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Static files settings
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Custom user model
AUTH_USER_MODEL = 'accounts.User'

# =============================================================================
# 团队协作配置说明
# =============================================================================
"""
团队共享配置说明：

1. 共享数据库：
   - 所有团队成员共享同一个数据库文件：team_shared.db
   - 数据库文件位于：项目根目录/shared_data/team_shared.db
   - 支持多用户并发访问，已配置线程安全

2. 会话管理：
   - 使用数据库存储会话，支持多个Django实例共享登录状态
   - 会话保持24小时

3. 缓存配置：
   - 使用文件缓存，提升多用户访问性能

4. 网络访问：
   - 已配置允许局域网内其他设备访问
   - 生产环境中应配置具体的IP地址而不是0.0.0.0

5. 使用方法：
   - 确保团队成员都能访问项目文件夹
   - 运行：python manage.py runserver 0.0.0.0:8000
   - 其他团队成员通过：http://[你的IP地址]:8000 访问

6. 注意事项：
   - 确保shared_data目录有适当的文件权限
   - 生产环境中应使用PostgreSQL或MySQL等专业数据库
   - 考虑数据备份策略
"""

# 日志配置（可选）
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': SHARED_DATA_DIR / 'django.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'accounts': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}
