# Generated by Django 5.1.2 on 2025-11-18 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='课程名称')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='课程代码')),
                ('course_type', models.CharField(choices=[('required', '必修课'), ('elective', '选修课'), ('practical', '实践课')], max_length=10, verbose_name='课程类型')),
                ('credits', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='学分')),
                ('hours', models.IntegerField(verbose_name='学时')),
                ('description', models.TextField(blank=True, null=True, verbose_name='课程描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='院系名称')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='院系代码')),
                ('description', models.TextField(blank=True, null=True, verbose_name='院系描述')),
                ('head_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='院系负责人')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='联系电话')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '院系',
                'verbose_name_plural': '院系',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='专业名称')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='专业代码')),
                ('duration', models.IntegerField(default=4, verbose_name='学制(年)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='专业描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.department', verbose_name='所属院系')),
            ],
            options={
                'verbose_name': '专业',
                'verbose_name_plural': '专业',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='学号')),
                ('real_name', models.CharField(max_length=50, verbose_name='真实姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性别')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('address', models.TextField(blank=True, null=True, verbose_name='家庭住址')),
                ('emergency_contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='紧急联系人')),
                ('emergency_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='紧急联系电话')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '学生档案',
                'verbose_name_plural': '学生档案',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='选课时间')),
                ('grade', models.CharField(blank=True, choices=[('A', '优秀 (90-100)'), ('B', '良好 (80-89)'), ('C', '中等 (70-79)'), ('D', '及格 (60-69)'), ('F', '不及格 (<60)')], max_length=1, null=True, verbose_name='成绩等级')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='分数')),
                ('semester', models.CharField(max_length=20, verbose_name='学期')),
                ('academic_year', models.CharField(max_length=10, verbose_name='学年')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.course', verbose_name='课程')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.major', verbose_name='专业')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile', verbose_name='学生')),
            ],
            options={
                'verbose_name': '选课记录',
                'verbose_name_plural': '选课记录',
                'unique_together': {('student', 'course', 'semester')},
            },
        ),
    ]
