# Generated by Django 5.2.8 on 2025-11-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentprofile_department_studentprofile_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='个人简介'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='class_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='个人邮箱'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='emergency_relation',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='与学生关系'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True, verbose_name='入学日期'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='enrollment_status',
            field=models.CharField(choices=[('enrolled', '在读'), ('suspended', '休学'), ('graduated', '已毕业'), ('dropped_out', '退学'), ('transferred', '转出')], default='enrolled', max_length=20, verbose_name='学籍状态'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='graduation_date',
            field=models.DateField(blank=True, null=True, verbose_name='预计毕业日期'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='hobbies',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='兴趣爱好'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='id_card_number',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='身份证号'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='nationality',
            field=models.CharField(default='汉族', max_length=20, verbose_name='民族'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='手机号码'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='political_status',
            field=models.CharField(blank=True, choices=[('', '请选择'), ('member', '党员'), ('probationary_member', '预备党员'), ('league_member', '团员'), ('masses', '群众')], max_length=20, null=True, verbose_name='政治面貌'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='skills',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='特长技能'),
        ),
    ]
