# Generated by Django 5.2.8 on 2025-11-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentprofile_bio_studentprofile_class_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='emergency_contact2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='紧急联系人2'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='emergency_phone2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='紧急联系电话2'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='emergency_relation2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='与学生关系2'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='紧急联系人1'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='紧急联系电话1'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='emergency_relation',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='与学生关系1'),
        ),
    ]
