# Generated by Django 5.2.8 on 2025-12-15 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studentprofile_emergency_contact2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='class_name',
        ),
    ]
