# Generated by Django 5.2.8 on 2025-12-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_class_name_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='academic_year',
            field=models.CharField(default='2024-2025', max_length=10, verbose_name='学年'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('1', '第1学期（大一上）'), ('2', '第2学期（大一下）'), ('3', '第3学期（大二上）'), ('4', '第4学期（大二下）'), ('5', '第5学期（大三上）'), ('6', '第6学期（大三下）'), ('7', '第7学期（大四上）'), ('8', '第8学期（大四下）')], default='1', max_length=2, verbose_name='开设学期'),
        ),
    ]
