# Generated by Django 5.2.8 on 2025-12-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_add_semester_academic_year_to_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='academic_year',
            field=models.CharField(choices=[('2020-2021', '2020-2021学年'), ('2021-2022', '2021-2022学年'), ('2022-2023', '2022-2023学年'), ('2023-2024', '2023-2024学年'), ('2024-2025', '2024-2025学年'), ('2025-2026', '2025-2026学年'), ('2026-2027', '2026-2027学年'), ('2027-2028', '2027-2028学年'), ('2028-2029', '2028-2029学年'), ('2029-2030', '2029-2030学年'), ('2030-2031', '2030-2031学年')], default='2024-2025', max_length=10, verbose_name='学年'),
        ),
    ]
