# Generated by Django 5.2.8 on 2025-12-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_course_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='current_academic_year',
            field=models.CharField(blank=True, choices=[('2020-2021', '2020-2021学年'), ('2021-2022', '2021-2022学年'), ('2022-2023', '2022-2023学年'), ('2023-2024', '2023-2024学年'), ('2024-2025', '2024-2025学年'), ('2025-2026', '2025-2026学年'), ('2026-2027', '2026-2027学年'), ('2027-2028', '2027-2028学年'), ('2028-2029', '2028-2029学年'), ('2029-2030', '2029-2030学年'), ('2030-2031', '2030-2031学年')], max_length=10, null=True, verbose_name='当前学年'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='current_semester',
            field=models.CharField(blank=True, choices=[('1', '第1学期（大一上）'), ('2', '第2学期（大一下）'), ('3', '第3学期（大二上）'), ('4', '第4学期（大二下）'), ('5', '第5学期（大三上）'), ('6', '第6学期（大三下）'), ('7', '第7学期（大四上）'), ('8', '第8学期（大四下）')], max_length=2, null=True, verbose_name='当前学期'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='grade_level',
            field=models.CharField(blank=True, choices=[('1', '大一'), ('2', '大二'), ('3', '大三'), ('4', '大四'), ('graduate', '研究生')], max_length=10, null=True, verbose_name='年级'),
        ),
    ]
