# Generated by Django 5.2.8 on 2025-12-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '管理员'), ('student', '学生')], default='student', max_length=10, verbose_name='角色'),
        ),
    ]
